version: '1.0' # Version number for this config

data-api-pipeline: 
  relative-location: '?/Data-API-Pipeline/processes' # Should be correct if you created the pipeline using CreateAPI.py
  git-branch-name: 'main' # We pull the current version of this branch if it is set. 
  data-file-location: API-Pipeline_last_run # no slashes before or after! One directory, not a tree.

database:
  name: '?SOME-API' # We require the name of the target database and project folder to be the same. Check if this is still true.
  server: 'some_db' # Including port number if not default
  connection-string-template: DRIVER={ODBC Driver 18 for SQL Server};SERVER={{database-server}};DATABASE={{database-name}};Trusted_Connection=yes;Encrypt=no;
  type: SQL-Server

concept-glossary:
  type: 'Rvk' # 'None' if no concept glossary is present.

latest:
    name: 'Nustada'
    relative-path: 'dbt/nustada' # No slashes before or after!

history:
  snapshot-date-column: 'sogu_dagur'
  projects:
    - project:
        source-schema: 'Nustada'
        snapshot-schema: 'Private_snapshot'
        public-schema: 'Saga'
    
# Used for both documentation creation and validation (BG/DD/dbt models)
public-schemas: # Schemas need to be case-correct
  - 'Nustada'
  - 'Saga'
  
documentation:
    publish-to: 'Confluence' # Only supported target right now!
    data-health-report:
      generate: False
      publish: False
    definition-health-report:
      generate: False
      publish: False
    user-documentation:
      generate: False
      publish: False

log-level: 'debug' # debug, warning, info, error, critical